[package]
name = "ucharge-server"
version = "0.1.0"
edition = "2021"

[dependencies]
http = { path = "../../libs/http" }
models = { path = "../../libs/models" }
tokio = { version = "1.44.2", features = ["full"] }
serde_json = "1.0.140"
sqlx = "0.8.3"
