[workspace]
resolver = "2"
members = [
	"server",
	"client",
	"libs/tcp",
	"libs/models", "libs/utils",
]

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # Only for testing purposes...
